### PR TITLE
Addition of getType() API

### PR DESCRIPTION
**Pull request by tpietzsch**
Changes that will be required after imglib/imglib2#312 is merged and released

### CODE REVIEW

**Comment by tpietzsch** [comment]
Bumping parent to pom-scijava-37.0.0 causes the following test failures with
`IllegalArgument Invalid service: net.imagej.legacy.LegacyService`

@ctrueden any idea what could be going on there and how to fix it?

```
[ERROR] Errors:
[ERROR]   GarbageCollectionTest.<init>:53 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   GarbageCollectionTest.<init>:53 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   InitialLabelingTest.testDoNotCrashWhenLabelingFileIsEmpty:62 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   InitialLabelingTest.testEnumeratedAxis:78 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   SegmentationUseCaseTest.test:78 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   SegmentationUseCaseTest.testMultiChannel:111 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   LabelingSerializationTest.<init>:69 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   LabelingSerializationTest.<init>:69 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   LabelingSerializationTest.<init>:69 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   LabelingSerializationTest.<init>:69 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   DefaultSegmentationModelTest.testListener:58 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   DefaultSegmentationModelTest.testLoadClassifierWithDifferentLabels:81 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   CalculateProbabilityMapWithLabkitIJ1PluginTest.test:21 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   CalculateProbabilityMapWithLabkitPluginTest.test:44 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   LabkitProbabilityMapForImagesInDirectoryPluginTest.<init>:71 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   LabkitSegmentImagesInDirectoryPluginTest.<init>:73 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   SegmentImageWithLabkitIJ1PluginTest.test:21 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   SegmentImageWithLabkitPluginTest.test:44 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   SegmentRGBImageTest.testSegmentation:61 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   SegmentRGBImageTest.testTraining:79 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   LabkitProjectFileSerializerTest.testOpen:59 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   LabkitProjectFileSerializerTest.testSave:47->exampleProject:84 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   SegmentationToolTest.<init>:51->openImage:81 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   SegmentationToolTest.<init>:51->openImage:81 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
[ERROR]   TrainableSegmentationSegmenterTest.testClassify3DStackInSlices:59 » IllegalArgument Invalid service: net.imagej.legacy.LegacyService
```

**Comment by maarzt** [comment]
@tpietzsch Thank you for the PR !!

What are the steps and timing required to get this released & deployed together with imglib2-7.1 ?

**Comment by tpietzsch** [comment]
It would be cool if you could make a release now. I'll ping you when the imglib2-7.1 is on the Fiji update site

**Comment by maarzt** [comment]
A made the releases:
* labkit-pixel-classification 0.1.18
* labkit-ui 0.4.0

@tpietzsch Could you please upload the labkit jars together with imglib2, I don't yet have the privileges to upload to Fiji's core update sites.

I also found a bug in imglib2-roi - imgLabeling.getType(). Even after fixing the bug `Utils.getType(imgLabeling).createVariable()` creates a LabelingType that behaves differently than with imglib2-6.1. Don't know why exactly.

**Pull request merged**
